# -*- mode: ruby *-*
# vi: set ft=ruby
VAGRANTFILE_API_VERSION = "2"

cluster = {
    "vm-1" => { :ip => "10.10.10.15", :cpus => 2, :mem => 2048 },
    #"vm-2" => { :ip => "10.10.10.21", :cpus => 1, :mem => 1024 },
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    config.ssh.insert_key = false
    config.vm.box = "bento/centos-8.1"

    if Vagrant.has_plugin?("vagrant-vbguest") then
	config.vbguest.auto_update = false
    end


    cluster.each do | hostname, specs |
        config.vm.define hostname do |node|
          node.vm.hostname = hostname
          node.vm.network :private_network, ip: specs[:ip]
          node.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
          node.vm.network "forwarded_port", guest: 443, host: 443, auto_correct: true

          #if specs.key?(:disk)
          #  node.disksize.size = specs[:disk]
          #end
          node.vm.provider :virtualbox do |vb|
            #vb.customize ['createhd', '--filename', specs[:disk], '--variant', 'Fixed', '--size', 5 * 1024]
            #vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', specs[:disk]]
            vb.customize ['modifyvm', :id, "--memory", specs[:mem], "--cpus", specs[:cpus]]

          end
        end
    end

end
